### Init Table

POST http://localhost:3000/modules/table HTTP/1.1

### Add Module

POST http://localhost:3000/modules HTTP/1.1
Content-Type: application/json

{
    "code": "ST0507",
    "name": "ADES",
    "credit": 6
}

### Get Modules

GET http://localhost:3000/modules/ST0507 HTTP/1.1

### Get Modules Bulk

GET http://localhost:3000/modules/bulk?codes=st0507,st0506,ades HTTP/1.1




<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leaflet Map Example</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
</head>

<body>
    <div id="map" style="height: 600px; width: 500px"></div>

    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script>
        // Sample locations
        // Sample locations
        const locations = [
            { name: "Singapore Poly", coordinates: [1.3187, 103.8451] },
            { name: "Blk 123 Teck Whye Lane", coordinates: [1.3788, 103.7526] }
            // Add more locations as needed
        ];

        // Calculate the average coordinates
        const averageLatitude = locations.reduce((sum, location) => sum + location.coordinates[0], 0) / locations.length;
        const averageLongitude = locations.reduce((sum, location) => sum + location.coordinates[1], 0) / locations.length;

        // Initialize the map with adjusted zoom level and centered around the average coordinates
        const map = L.map('map').setView([averageLatitude, averageLongitude], 14);

        // Add a tile layer (OpenStreetMap)
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; OpenStreetMap contributors'
        }).addTo(map);

        // Add markers for each location
        locations.forEach(location => {
            L.marker(location.coordinates).addTo(map).bindPopup(location.name);
        });
    </script>
</body>

</html>